apiVersion: v1
kind: Service
metadata:
  name: capstone-devops
  labels:
    app: capstone-devops
spec:
  ports:
  - name: "8000"
    port: 8000 # port of the serivce
    targetPort: 80 # port of the container that service will forward to 
    protocol: TCP
  selector:
    app: capstone-devops
    version: v2
  type: LoadBalancer