apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-devops-blue
  labels:
    app: capstone-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-devops
  template:
    metadata:
      labels:
        app: capstone-devops
        version: v1
    spec:
      containers:
      - name: capstone-devops
        image: linhcnse130515/capstone-devops:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "200m"