apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-devops
  labels:
    app: capstone-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-devops
  template:
    metadata:
      labels:
        app: capstone-devops
        role: rolling-update
    spec:
      containers:
        - image: linhcnse130515/capstone-devops
          name: capstone-devops
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1