apiVersion: v1
kind: Service
metadata:
  name: capstone-devops
  labels: 
    app: capstone-devops
spec:
  selector:
    app: capstone-devops
  ports:
    - port: 8000
      targetPort: 80
  type: LoadBalancer